apiVersion: apps/v1
kind: Deployment 
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp 
  template:
    metadata:
      name: javawebappdeployment
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:1
      ports:
      - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: deploymentservice 
spec: 
  type: NodePort 
  selector: 
    app: javawebapp 
  ports: 
  - port: 80
    targetPort: 8080
    nodePort: 31234
