apiVersion: apps/v1
kind: Deployment 
metadata: 
   name: hpadeploymentdemo
spec: 
  replicas: 3
  selector:
    matchLabels:
     app: hpapod 
  template:
    metadata:
      name: hpapod 
    spec:
      containers:
      - name: javawebcontainers
        image: dockerhandson/java-web-app:1
        ports:
        - name: java
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hpaservice
spec:
  type: NodePort
  selector:
    app: hpapod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31234
---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoScaler
metadata:
  name: hpadeploymentscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpadeploymentdemo
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 50
        type: Resource
