apiVersion: apps/v1
kind: Deployment 
metadata:
  name: hpadeployment 
  labels:
    app: hpapod
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: hpapod
  template:
    metadata:
      labels:
        app: hpapod 
    spec:
      containers: 
      - name: hpacontainer 
        image: k8s.gcr.io/hpa-example
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits: 
            cpu: "100m"
            memory: "256Mi"
            