apiVersion: apps/v1
kind: Deployment
metadata:
   name: hpadeployment
   labels:
   name: hpadeployment
spec:
  replicas: 2
  selector:
    matchLables:
	   app: hpadeployment
  template:
    metadata:
	    name: hpadeploymentpod
	    labels:
	      app: hpadeployment
    spec:
	    containers:
	    - name: hpadeploymentcontainer
	    image: dockerhandson/java-web-app
		  ports:
		  - port: 80
		  targetPort: 8080
		  resource:
		    requests:
		      cpu: 100m
			    memory: 64Mi
		    limits:
		      cpu: 200m
			    memory: 256Mi