apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.30.1.133
    path: "/mnt/share"
