apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webserver
spec:
  containers:
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: nginxservice
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
  - port: 80
    targetPort: 80

