apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  replicas: 2
  template:
    name: javawebapp
    metadata:
      name: javawebapp
    spec:
      containers: 
        - name: javawebapp 
          image: dockerhandson/java-web-app
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service 
metadata:
  name: javaservice 
spec:
  type: NodePort
  selector: 
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
